name: WhiteBirdPvP
version: 1.1.0
main: com.github.niwaniwa.whitebird.pvp.WhiteBirdPvP
commands:
  whitebirdpvp:
  arena:
  duel:
  accept:
  maps:
  spawn:
  leave:
  namechange:
  match:
  getInventory: